name: Default environment variables

on:
  push:
  
jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/index.php DEMO.php.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Print outfile content
        run: cat $HOME/index.php

  default-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Testing secrets
        run: |
          if [ "$Devops" == "dillibabu91GIT" ]; then
            echo "got our secret"
          fi
        env:
          Devops: "${{ secrets.SECRETS_TOKEN }}"
          
      - name: Default environment variables
        run: |
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "RUNNER_OS: ${RUNNER_OS}"

